import type { Translations } from '@/types';

export const pt: Translations = {
  appName: "LESDB",
  tagline: "Banco de Dados de Filmes Sáficos",
  searchPlaceholder: "Buscar filmes, atrizes, diretoras...",
  filterBy: "Filtrar por",
  releaseYear: "Ano de Lançamento",
  country: "País",
  language: "Idioma",
  tags: "Tags", // Referenciará primariamente Gêneros do TMDB
  all: "Todos",
  allCountries: "Todos os Países",
  allLanguages: "Todos os Idiomas",
  resetFilters: "Limpar Filtros",
  sortBy: "Ordenar por",
  sortOptions: {
    titleAsc: "Título (A-Z)",
    titleDesc: "Título (Z-A)",
    yearNewest: "Ano (Mais Novo)",
    yearOldest: "Ano (Mais Antigo)",
    imdbHighest: "Nota IMDb (Maior)",
    imdbLowest: "Nota IMDb (Menor)",
  },
  availability: "Disponibilidade",
  noMoviesFound: "Nenhum filme encontrado com seus critérios.",
  noMoviesFoundForIDs: "Parece que o TMDB não retornou filmes para os IDs especificados ou eles foram filtrados. Verifique sua chave da API do TMDB em <code>.env.local</code>, certifique-se de que o servidor foi reiniciado e inspecione os logs do console do servidor para \"Raw data from TMDB\".",
  loadingMoreMovies: "Carregando mais filmes...",
  loadingMovies: "Carregando filmes...",
  selectLanguage: "Selecionar Idioma",
  english: "English",
  portuguese: "Português (Brasil)",
  showFilters: "Mostrar Filtros",
  hideFilters: "Esconder Filtros",
  movieCard: {
    year: "Ano",
    countries: "Países",
    languages: "Idiomas",
    tags: "Gêneros", // Alterado de Tags para Gêneros
    director: "Direção",
    description: "Descrição",
  },
  tmdbError: "Opa! Não foi possível buscar os filmes do TMDB.",
  tmdbErrorSuggestion: "Exibindo filmes de exemplo. Verifique sua chave da API do TMDB ou tente novamente mais tarde.",
  pagination: {
    previousPage: "Página Anterior",
    nextPage: "Próxima Página",
    pageInfo: "Página {{currentPage}} de {{totalPages}}",
  },
  countries: {
    USA: "EUA",
    US: "EUA",
    Brazil: "Brasil",
    BR: "Brasil",
    Canada: "Canadá",
    CA: "Canadá",
    UK: "Reino Unido",
    GB: "Reino Unido",
    France: "França",
    FR: "França",
    Germany: "Alemanha",
    DE: "Alemanha",
    Spain: "Espanha",
    ES: "Espanha",
    Argentina: "Argentina",
    AR: "Argentina",
    SouthKorea: "Coreia do Sul",
    KR: "Coreia do Sul",
    Sweden: "Suécia",
    SE: "Suécia",
    Australia: "Austrália",
    AU: "Austrália",
    Belgium: "Bélgica",
    BE: "Bélgica",
    Kenya: "Quênia",
    KE: "Quênia",
    SouthAfrica: "África do Sul",
    ZA: "África do Sul",
    Norway: "Noruega",
    NO: "Noruega",
    Lebanon: "Líbano",
    LB: "Líbano",
    Netherlands: "Holanda",
    NL: "Holanda",
    JP: "Japão",
    CN: "China",
  },
  languages: {
    English: "Inglês",
    EN: "Inglês",
    Portuguese: "Português",
    PT: "Português",
    Spanish: "Espanhol",
    ES: "Espanhol",
    French: "Francês",
    FR: "Francês",
    German: "Alemão",
    DE: "Alemão",
    Korean: "Coreano",
    KO: "Coreano",
    Swedish: "Sueco",
    SV: "Sueco",
    Mandarin: "Mandarim",
    ZH: "Mandarim",
    Japanese: "Japonês",
    JA: "Japonês",
    Swahili: "Suaíli",
    SW: "Suaíli",
  },
  movieTags: { // Tags agora são primariamente para Gêneros do TMDB
    "Action": "Ação",
    "Adventure": "Aventura",
    "Animation": "Animação",
    "Comedy": "Comédia",
    "Crime": "Crime",
    "Documentary": "Documentário",
    "Drama": "Drama",
    "Family": "Família",
    "Fantasy": "Fantasia",
    "History": "História",
    "Horror": "Terror",
    "Music": "Música",
    "Mystery": "Mistério",
    "Romance": "Romance",
    "Science Fiction": "Ficção Científica",
    "TV Movie": "Filme para TV",
    "Thriller": "Suspense",
    "War": "Guerra",
    "Western": "Faroeste",
     // Mantendo algumas tags definidas anteriormente que podem sobrepor com gêneros do TMDB ou para dados de exemplo
    "Period Drama": "Drama de Época",
    "Coming of Age": "Amadurecimento",
    "Based on a Book": "Baseado em Livro",
    // Tags específicas da IA removidas (ex: "Final Feliz", "Representação POC", etc.)
    // pois a classificação por IA foi removida. O usuário irá gerenciá-las via SQL.
    sapphic: "Sáfico",
    lesbian: "Lésbico",
  },
  platforms: {
    Netflix: "Netflix",
    PrimeVideo: "Prime Video",
    Hulu: "Hulu",
    HBOMax: "HBO Max",
    AppleTV: "Apple TV+",
    Mubi: "Mubi",
    Other: "Outro",
  },
  about: "Sobre",
  aboutPageTitle: "Sobre o LESDB",
  aboutPageParagraph1: "LESDB é um banco de dados dedicado a filmes sáficos de todo o mundo. Nosso objetivo é fornecer um recurso abrangente para descobrir, explorar e celebrar filmes que apresentam histórias e relacionamentos de mulheres lésbicas, bissexuais, pansexuais e outras mulheres queer.",
  aboutPageParagraph2: "Este projeto é um trabalho feito com amor, visando facilitar ao público encontrar filmes que ressoem com eles. Utilizamos o TMDB para dados de filmes e IA para classificação de tags para enriquecer a experiência de navegação. Explore, descubra e aproveite o mundo do cinema sáfico!",
};